baseURL = "https://ferdynton.github.io/"
title = "Code and Stuff"
languageCode = "en-US"
theme = "hyde-y"

[params.author]
  name = "Fernando Seror"
  email = "ferdynton@gmail.com"

[params]
  disqusShortname = "ferdynton"
  brand = "Ferdynton"
  topline = "At least computers read me"

  sidebar = "left"

  # Text for the top menu link, which goes the root URL for the site.
  home = "Home"

  # Sidebar social links.
  github = "ferdynton"
  linkedin = "fseror"
  twitter = "Ferdy89"

  rss = true
